def handleFailure(self, test, err):
    '\n        Adds Failing test cases and information to log.\n        '
    self.printMsg(FAILED, self.__testName, GetDetailExceptionInfo(err))
    self.__testResult = FAILED
