{
  if (!_resource.start()) {
    s_logger.error("Unable to start the resource: " + _resource.getName());
    throw new CloudRuntimeException("Unable to start the resource: " + _resource.getName());
  }
  try {
    _connection.start();
  }
 catch (  final NioConnectionException e) {
    s_logger.warn("NIO Connection Exception  " + e);
    s_logger.info("Attempted to connect to the server, but received an unexpected exception, trying again...");
  }
  while (!_connection.isStartup()) {
    _shell.getBackoffAlgorithm().waitBeforeRetry();
    _connection=new NioClient("Agent",_shell.getHost(),_shell.getPort(),_shell.getWorkers(),this);
    try {
      _connection.start();
    }
 catch (    final NioConnectionException e) {
      s_logger.warn("NIO Connection Exception  " + e);
      s_logger.info("Attempted to connect to the server, but received an unexpected exception, trying again...");
    }
  }
}
