def create_vm(self, networkid=None, pfrule=False, egress_policy=True, RR=False):
    self.create_network_offering(egress_policy, RR)
    self.debug(('Creating network with network offering: %s' % self.network_offering.id))
    self.network = Network.create(self.apiclient, self.services['network'], accountid=self.account.name, domainid=self.account.domainid, networkofferingid=self.network_offering.id, zoneid=self.zone.id)
    self.debug(('Created network with ID: %s' % self.network.id))
    self.debug(('Deploying instance in the account: %s' % self.account.name))
    project = None
    try:
        self.virtual_machine = VirtualMachine.create(self.apiclient, self.services['virtual_machine'], accountid=self.account.name, domainid=self.domain.id, serviceofferingid=self.service_offering.id, mode=(self.zone.networktype if pfrule else 'basic'), networkids=[str(self.network.id)], projectid=(project.id if project else None))
    except Exception as e:
        self.debug(('error=%s' % e))
    self.debug(('Deployed instance in account: %s' % self.account.name))
