@attr(tags=['advanced'], required_hardware='false')
def test_deployVM_in_sharedNetwork_as_admin_scope_account_differentdomain(self):
    '\n\tValiate that ROOT admin is NOT able to deploy a VM for a admin user in a shared network with scope=account which the admin user does not have access to\n\t'
    self.apiclient.connection.apiKey = self.default_apikey
    self.apiclient.connection.securityKey = self.default_secretkey
    self.vmdata['name'] = (self.acldata['vmD2A']['name'] + '-shared-scope-account-root-admin')
    self.vmdata['displayname'] = (self.acldata['vmD2A']['displayname'] + '-shared-scope-account-root-admin')
    try:
        vm = VirtualMachine.create(self.apiclient, self.vmdata, zoneid=self.zone.id, serviceofferingid=self.service_offering.id, templateid=self.template.id, networkids=self.shared_network_account_d111a.id, accountid=self.account_d2a.name, domainid=self.account_d2a.domainid)
        self.fail('ROOT admin is able to deploy a VM for a admin user in a shared network with scope=account which the admin user does not have access to')
    except Exception as e:
        self.debug(('account %s' % e))
        if (not CloudstackAclException.verifyMsginException(e, CloudstackAclException.UNABLE_TO_USE_NETWORK)):
            self.fail('Error message validation failed when ROOT admin tries to deploy a VM for a admin user in a shared network with scope=account which the admin user does not have access to ')
