def handleError(self, test, err):
    '\n        Adds Exception throwing test cases and information to log.\n        '
    err_msg = GetDetailExceptionInfo(err)
    self.tcRunLogger.fatal(('%s: %s: %s' % (EXCEPTION, self.testName, err_msg)))
    self.testResult = EXCEPTION
