def updateNetwork(self, conn):
    try:
        self.network.update(self.api_client, networkofferingid=self.network_offering_for_update.id, updateinsequence=True, forced=True, changecidr=False)
    except Exception as e:
        conn.send(('Failed to update network: %s due to %s' % (self.network.name, e)))
    conn.send('update Network Complete')
    return
