{
  try {
    final LdapContext context=_ldapContextFactory.createUserContext(principal,password);
    closeContext(context);
    return true;
  }
 catch (  NamingException|IOException e) {
    s_logger.debug("Exception while doing an LDAP bind for user " + " " + principal,e);
    s_logger.info("Failed to authenticate user: " + principal + ". incorrect password.");
    return false;
  }
}
